FROM --platform=linux/amd64 ubuntu:20.04 as builder
RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y make gcc bison flex

COPY . /mc
WORKDIR /mc
RUN ./configure --prefix=/install
RUN make bootstrap
RUN make
RUN make install

FROM ubuntu:20.04 as package

COPY --from=builder /install /install
